// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jwt.actions;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.Reader;
import java.io.StringReader;
import org.bouncycastle.util.io.pem.PemObject;
import org.bouncycastle.util.io.pem.PemReader;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

import jwt.proxies.JWTRSAPrivateKey;
import jwt.proxies.JWTRSAPublicKey;
import system.proxies.FileDocument;

import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ConvertPEMtoDER extends CustomJavaAction<IMendixObject>
{
	private java.lang.String pemKey;
	private jwt.proxies.ENU_KeyType keyType;

	public ConvertPEMtoDER(IContext context, java.lang.String pemKey, java.lang.String keyType)
	{
		super(context);
		this.pemKey = pemKey;
		this.keyType = keyType == null ? null : jwt.proxies.ENU_KeyType.valueOf(keyType);
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		Reader reader = new StringReader(pemKey);
		PemReader pemReader = new PemReader(reader);
		PemObject pemObject = pemReader.readPemObject();
		
		byte[] pemBytes = pemObject.getContent();
		InputStream inputStream = new ByteArrayInputStream(pemBytes);
		
		FileDocument derKey = null;;
		
		try {
			switch(keyType) {
			case _Private:
				derKey = new JWTRSAPrivateKey(context);
				break;
			case _Public:
				derKey = new JWTRSAPublicKey(context);
				break;
				default:
					throw new CoreException("Please specify a key type.");
			}
			
			Core.storeFileDocumentContent(context, derKey.getMendixObject(), inputStream);
		} finally {
			if (pemReader != null) {
				pemReader.close();
			}
			
			if (inputStream != null) {
				inputStream.close();
			}
		}
		
		return derKey.getMendixObject();
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ConvertPEMtoDER";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
