// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jwt.actions;

import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class ExtractPublicKeyInformation extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __publicKey;
	private jwt.proxies.JWTRSAPublicKey publicKey;

	public ExtractPublicKeyInformation(IContext context, IMendixObject publicKey)
	{
		super(context);
		this.__publicKey = publicKey;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.publicKey = __publicKey == null ? null : jwt.proxies.JWTRSAPublicKey.initialize(getContext(), __publicKey);

		// BEGIN USER CODE
		CertificateFactory factory = CertificateFactory.getInstance("X.509");
		X509Certificate cert = (X509Certificate) factory.generateCertificate(
				Core.getFileDocumentContent(getContext(), publicKey.getMendixObject()));
		publicKey.setIssuer(cert.getIssuerDN().getName());
		publicKey.setSubject(cert.getSubjectDN().getName());
		publicKey.setValidUntil(cert.getNotAfter());
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExtractPublicKeyInformation";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
