// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jwt.actions;

import java.io.ByteArrayInputStream;
import java.math.BigInteger;
import java.security.KeyFactory;
import java.security.interfaces.RSAPrivateKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.RSAPrivateKeySpec;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GenerateRSAPrivateKey extends CustomJavaAction<IMendixObject>
{
	private java.lang.String modulus;
	private java.lang.String privateExponent;

	public GenerateRSAPrivateKey(IContext context, java.lang.String modulus, java.lang.String privateExponent)
	{
		super(context);
		this.modulus = modulus;
		this.privateExponent = privateExponent;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		KeyFactory keyFactory = KeyFactory.getInstance("RSA");
		RSAPrivateKeySpec privateKeySpec = new RSAPrivateKeySpec(new BigInteger(modulus), new BigInteger(privateExponent));
		RSAPrivateKey rsaPrivateKey = (RSAPrivateKey) keyFactory.generatePrivate(privateKeySpec);
		PKCS8EncodedKeySpec pkcs8EncodedKeySpec = new PKCS8EncodedKeySpec(rsaPrivateKey.getEncoded());
		jwt.proxies.PrivateKey privateKey = new jwt.proxies.PrivateKey(this.context());
		Core.commit(this.context(), privateKey.getMendixObject());
		Core.storeFileDocumentContent(this.context(), privateKey.getMendixObject(), new ByteArrayInputStream(pkcs8EncodedKeySpec.getEncoded()));
		return privateKey.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GenerateRSAPrivateKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
